[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r backend/simple_requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python backend/simple_main.py"
