[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r backend/simple_requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python backend/simple_main.py"
